version: '2'
services:
  practicenext:
    image: "ajsurfco/practicenext:0.1"
    ports:
      - "8091:8000"
    volumes:
      - /srv/docker/practicenext/html:/srv/public
    restart: always
#    depends_on:
#      - couchdb
    deploy:
      resources:
        limits:
          memory: 500M
#  couchdb:
#    image: couchdb:3.3
#    ports:
#      - "5984:5984"  # CouchDB default port
#    environment:
#      COUCHDB_USER: admin
#      COUCHDB_PASSWORD: password
#    volumes:
#      - /srv/docker/practicenext/db:/opt/couchdb/data
#    restart: always

